"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q)g_kfm_wt^b1cyntjiq_wq@!pe%!$3)fx9yloj%*=b6knn(^9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'user.apps.UserConfig',
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
    'goods.apps.GoodsConfig',
    'tinymce',
    'haystack',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# CREATE DATABASE `ecommerce` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerce',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # 静态文件目录

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 启用自定义用户模型 使用django内置用户认证系统
AUTH_USER_MODEL = 'user.User'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# login_required装饰器 LoginRequiredMixin类 重定向登录url
LOGIN_URL = '/user/login/'

# 发送邮件的配置
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 控制台后端仅将邮件发送至标准输出(测试用)
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '2230979122@qq.com'  # 发送邮件的邮箱
EMAIL_HOST_PASSWORD = 'jwdjkuluhzalebfd'  # 在邮箱中设置的客户端授权密码
EMAIL_USE_SSL = True  # 与 SMTP 服务器对话使用隐式 TLS（安全）连接

# django-redis 作为cache后端配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "history": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}
# django-redis 作为session后端配置
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# celery配置
CELERY_BROKER_URL = 'redis://localhost:6379/2'
CELERY_TIMEZONE = "Asia/Shanghai"
# Only add pickle to this list if your broker is secured from unwanted access (see userguide/security.html)
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'

# FastDFS分布式文件系统配置
DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'  # 配置文件存储类
FDFS_CLIENT_CONF = '/etc/fdfs/client.conf'  # 配置fdfs客户端配置文件路径
FDFS_SERVER_URL = 'http://0.0.0.0:8888/'  # 配置fdfs存储服务器上Nginx的ip和端口号

# 全文检索框架配置
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',  # 使用whoosh引擎
        'PATH': BASE_DIR / 'whoosh_index',  # 索引文件路径
    }
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'  # 当添加 修改 删除数据时，自动生成索引
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 5  # 控制搜索结果每页显示的数量

"""
# 其它命令
python manage.py makemigration
python manage.py migrate
python manage.py rebuild_index  # 生成索引文件

# 启动项目
sudo fdfs_trackerd /etc/fdfs/tracker.conf restart  # 启动tracker
sudo fdfs_storaged /etc/fdfs/storage.conf restart  # 启动storage
sudo /usr/local/nginx/sbin/nginx  # 启动nginx
redis-server
celery -A ecommerce worker -l INFO -P eventlet
py manage.py runserver [::]:8469

# 支付宝沙箱账号密码
qoqamp8198@sandbox.com
111111

# todo:fix-bug
首页焦点图 只有一张会左右切换会有白屏
商品详情页 立即购买 加入购物车 按钮超出区域
商品详情页 立即购买 按钮点击无效
支付接口 同步查询问题
用户中心-全部订单-待评价按钮 多个订单按钮均指向第一个待评价订单 也会导致重复评价问题
搜索页面购物车 不显示数量
搜索页面 商品分类不显示
"""
